### ISSUE TITLE
这么好的工具竟然只有7个star，我都想多注册几个账号来点赞了！

### ISSUE THREAD

**Issue by xieranmaya** [xwartz/Auto-Spacing#1]
RT

**Comment by xwartz** [comment]
哈哈  谢谢

**Comment by xieranmaya** [comment]
用了两天，提个建议哈，目前貌似是直接把文件本身给替换了，然后 Sublime 会提示说文件内容有改变，是否需要重新加载，一般这种格式化的工具都是直接更改当前正在编辑的状态并替换掉编辑器里当前的内容。
目前的做法可能会导致特殊情况下丢失数据：
比如说很久没存盘了，然后运行一下auto spacing，然后磁盘上的文件被替换，编辑器提示加载新的文件，然后用户点了确定，没存盘的内容是否就会丢失呢？

**Comment by xwartz** [comment]
这个我可以研究下 sublime 提供的 API

**Comment by xwartz** [comment]
@xieranmaya   已经更新了

**Comment by xieranmaya** [comment]
赞啊！速度真快！！已更新~
